RecordFCS/RecordFCS/Controllers/ListadoController.cs
using RecordFCS.Models;
using RecordFCS.Models.ViewsModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecordFCS.Helpers;

namespace RecordFCS.Controllers
{
    public class ListadoController : BaseController
    {
        private RecordFCSContext db = new RecordFCSContext();

        // GET: Listado
        public ActionResult Index()
        {
            //Mostrar los atributos que sean lista para tratarlos
            //var lista = db.TipoAtributos.Where(a=> a.EsLista && a.Status).OrderBy(a=> a.BuscadorOrden);
            //List<PiezaEnCarrito> listaPiezas = new List<PiezaEnCarrito>();

            //ViewBag.listaPiezas = (List<PiezaEnCarrito>)Session["listaDePiezas"];

            var x = db.Piezas.Take(15).ToList();
            //ViewBag.ListaP = x;

            Session["listaP"] = x;

            return View();
        }


        public ActionResult PiezaAdd(Int64 PiezaID, string NombreLista = "listaTemporal")
        {
            //string mensaje = "";
            var lista = Session[NombreLista] == null ? new List<PiezaEnCarrito>() : (List<PiezaEnCarrito>)Session[NombreLista];
            var recarga = true;
            PiezaEnCarrito pcarrito = lista.SingleOrDefault(a => a.PiezaID == PiezaID);

            if (pcarrito == null)
            {
                pcarrito = ValidarAdd(PiezaID);
                if (pcarrito != null)
                {
                    //agregar la pcarrito a la lista
                    lista.Add(pcarrito);
                    Session[NombreLista] = lista.OrderBy(a => a.ObraID).ThenBy(a => a.PiezaID).ToList();
                    AlertaSuccess(string.Format("({0}) {1} - Se agregó en <b>{2}</b>", pcarrito.PiezaID, pcarrito.Titulo, NombreLista), true);
                }
                else
                {
                    AlertaInverse(string.Format("({0}) - Error. No se puede agregar esta pieza en <b>{1}</b>", PiezaID, NombreLista), true);
                    recarga = false;
                }
            }
            else
            {
                AlertaInverse(string.Format("({0}) {1} - Ya esta en <b>{2}</b>", pcarrito.PiezaID, pcarrito.Titulo, NombreLista), true);
                recarga = false;
            }

            return Json(new { success = true, lista = NombreLista, recarga = recarga }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult PiezaDel(Int64 PiezaID, string NombreLista = "listaTemporal")
        {
            //string mensaje = "";
            var lista = Session[NombreLista] == null ? new List<PiezaEnCarrito>() : (List<PiezaEnCarrito>)Session[NombreLista];
            var recarga = true;

            PiezaEnCarrito pcarrito = lista.SingleOrDefault(a => a.PiezaID == PiezaID);

            if (lista.Remove(pcarrito))
            {
                AlertaWarning(string.Format("({0}) {1} - Se eliminó de <b>{2}</b>", pcarrito.PiezaID, pcarrito.Titulo, NombreLista), true);
            }
            else
            {
                AlertaInverse(string.Format("({0}) - Error. No se puede eliminar esta pieza de <b>{1}</b>", PiezaID, NombreLista), true);
                recarga = false;
            }

            return Json(new { success = true, lista = NombreLista, recarga = recarga }, JsonRequestBehavior.AllowGet);
        }


        public PiezaEnCarrito ValidarAdd(Int64 PiezaID)
        {
            PiezaEnCarrito piezaEnCarrito = null;
            var pieza = db.Piezas.Where(a => a.PiezaID == PiezaID).
                Select(a => new
                {
                    a.PiezaID,
                    a.ObraID,
                    ClavePieza = a.Clave,
                    ClaveObra = a.Obra.Clave,
                    Titulo = a.AtributoPiezas.FirstOrDefault(b => b.Atributo.TipoAtributo.AntNombre == "titulo").Valor,
                    Autor = a.AutorPiezas.Select(c => c.Autor.Nombre + " " + c.Autor.Apellido).FirstOrDefault(),
                    Imagen = a.ImagenPiezas.FirstOrDefault()
                }).FirstOrDefault();

            if (pieza != null)
            {
                piezaEnCarrito = new PiezaEnCarrito()
                {
                    ObraID = pieza.ObraID,
                    ClaveObra = pieza.ClaveObra,
                    PiezaID = pieza.PiezaID,
                    ClavePieza = pieza.ClavePieza,
                    Titulo = pieza.Titulo,
                    Autor = pieza.Autor,
                    RutaImagen = pieza.Imagen == null ? RutaImagen.RutaMini_Default : pieza.Imagen.RutaThumb
                };

            }
            return piezaEnCarrito;
        }


        public ActionResult RenderListaTemporal(string NombreLista = "listaTemporal")
        {
            var lista = Session[NombreLista] == null ? new List<PiezaEnCarrito>() : (List<PiezaEnCarrito>)Session[NombreLista];

            var listaAgrupada = lista.GroupBy(a => a.ObraID).ToList();





            //return Json(new { success = true, total = lista.Count, lista = NombreLista});
            ViewBag.totalLT = lista.Count;
            return PartialView("_ListaTemporal", listaAgrupada);
        }


        public ActionResult MenuImprimir(string Accion = "Plano", string NombreLista = "listaDefault")
        {
            var opcion = new OpcionesImprimir()
            {
                Accion = Accion,
                NombreLista = NombreLista,
                Fecha = true,
                Ubicacion = false,
                Unir = 0,
                IncluirPiezas = false,
                FondoAgua = true,
                NoColumnas = 1,
                Linea = 0,
                MostrarDatos = 0,
                NombreLogotipo = 1
            };

            //saber cuantos registros tiene la lista Default

            var lista = Session[opcion.NombreLista] == null ? new List<long>() : (List<long>)Session[opcion.NombreLista];

            opcion.NoElementos = lista.Count;



            return PartialView("_MenuImprimir", opcion);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GenerarFormato(OpcionesImprimir opcion)
        {
            var vista = PartialView();

            var listadePiezasID = Session[opcion.NombreLista] == null ? new List<long>() : (List<long>)Session[opcion.NombreLista];
            IQueryable<Pieza> listaPiezas = null;

            //listado default plano o excel
            List<itemListaBasicaDefault> listaBasicaDefault = new List<itemListaBasicaDefault>();
            List<itemPiezaGenerica> listaPiezasGenerica = new List<itemPiezaGenerica>();
            //listado 


            //opcion incluir todas las piezas 
            if (opcion.IncluirPiezas)
            {
                var listadeObrasID = db.Obras.Where(a => a.Piezas.Any(b => listadePiezasID.Contains(b.PiezaID))).Select(c => c.ObraID).ToList();
                listaPiezas = db.Piezas.Where(a => listadeObrasID.Contains(a.ObraID));
            }
            else
            {
                listaPiezas = db.Piezas.Where(a => listadePiezasID.Contains(a.PiezaID));
            }


            //opcion datos basicos o completos
            switch (opcion.Accion)
            {
                case "Word":
                case "Imprimir":
                case "Etiqueta":

                    //Basicos - FichaBasica
                    //saber cuales son los atributos basicos de cada pieza
                    foreach (var grupo in listaPiezas.GroupBy(a => a.TipoPieza).ToList())
                    {
                        IEnumerable<Atributo> listaAtributos = null;

                        if (opcion.MostrarDatos == 0)
                            listaAtributos = grupo.Key.Atributos.Where(a => a.EnFichaBasica && a.Status).OrderBy(b => b.Orden).ToList();
                        else
                            listaAtributos = grupo.Key.Atributos.Where(a => a.Status).ToList();

                        //recorrer pieza a pieza
                        foreach (var pieza in grupo)
                        {
                            //crear pieza generica
                            var x = new itemPiezaGenerica()
                            {
                                ObraID = pieza.ObraID,
                                ObraClave = pieza.Obra.Clave,
                                PiezaID = pieza.PiezaID,
                                PiezaClave = pieza.Clave,
                                itemPiezaGenericaCampos = new List<itemPiezaGenericaCampo>()
                            };

                            //agregar sus atributos
                            foreach (var att in listaAtributos)
                            {
                                var campo = new itemPiezaGenericaCampo()
                                {
                                    itemPiezaGenerica = x,
                                    PiezaID = x.PiezaID,
                                    NombreCampo = att.TipoAtributo.Nombre,
                                    Orden = att.Orden
                                };

                                //extraer los valores

                                switch (att.TipoAtributo.AntNombre)
                                {
                                    case "TipoObjeto_Clave":
                                        campo.ValorCampo = pieza.Obra.TipoObra.Nombre;
                                        break;
                                    case "TipoPieza_Clave":
                                        campo.ValorCampo = pieza.TipoPieza.Nombre;
                                        break;
                                    case "m_pieza_coleccion":
                                        if (pieza.Obra.ColeccionID != null)
                                            campo.ValorCampo = pieza.Obra.Coleccion.Nombre;
                                        break;
                                    case "ClassColeccion_Clave":

RecordFCS/RecordFCS/Views/Listado/Index.cshtml
@using RecordFCS.Models
@using RecordFCS.Models.ViewsModel
@using RecordFCS.Helpers

@{
    ViewBag.Title = "Generar Listas";
}

<h1>
    <b>Generar Listas de Obras ó Piezas</b>
</h1>

<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="active">@ViewBag.Title</li>
</ol>


<div class="row">

    <div class="col-lg-3 col-md-3 col-sm-3">

        <div id="TabAcciones" class="tab-content">
            <div class="tab-pane fade active in" id="MenuAcciones">
                ACCIONES A REALIZAR
                <ul>
                    <li>Agregarlas a Coleccion</li>
                    <li>Agregarlas a Exposición (Guión)</li>
                    <li>Activarlas</li>
                    <li>Desactivarlas</li>
                    <li>Generar Movimiento</li>
                </ul>
                <a href="#FormAcciones" data-toggle="tab" aria-expanded="false">Mostrar Formulario</a>

                <div id="renderMenuFiltros">
                    @{ Html.RenderAction("MenuFiltros", "Buscador", new { rutaVista = "_ResultadosBusqueda_Listado" }); }
                </div>

            </div>

            <div class="tab-pane fade" id="FormAcciones">

                FORMULARIO PARA CADA ACCION
                <a href="#MenuAcciones" data-toggle="tab" aria-expanded="false">Regresar</a>

            </div>
        </div>



    </div>


    <div class="col-lg-9 col-md-9 col-sm-9">

        <div class="col-lg-6 col-md-6 col-sm-6">


            <h4>
                <b class="text-muted">Resultado de Piezas</b>
            </h4>


            <div id="render_resultadoPiezas">
                @*<ul>
                    @foreach (var item in Session["listaP"] as List<Pieza>)
                    {
                        <li>
                            @Html.ActionLink(item.PiezaID.ToString(), "PiezaAdd", "Listado", new { PiezaID = item.PiezaID }, new { @Class = "llamarRenderLTAdd" })
                        </li>
                    }
                </ul>*@
            </div>
        </div>


        <div class="col-lg-6 col-md-6 col-sm-6">
            <div id="contenedor_ListaTemporal" class="">
                <div class="contentlt_head">
                    <h4>
                        <b class="text-muted">Nueva Lista Temporal</b>
                        <span class="link link-success fa fa-08x fa-refresh" id="recargaListaTemporal" data-toggle="tooltip" title="Recargar Lista"></span>
                        <span id="TotalLT" data-toggle="tooltip" title="Mostrar/Ocultar" class="badge pull-right MOLT">0</span>
                    </h4>
                </div>

                <div id="render_listaTemporal">

                </div>

                <span id="MOLT" data-toggle="tooltip" title="Mostrar/Ocultar" class="fa fa-expand fa-flip-horizontal"></span>
            </div>
        </div>

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

<script type="text/javascript">

    window.onload = RecargaListaTemporal();



    function enviarInfoAjaxyRecargaLT(link) {
        $.ajax({
            url: link,
            type: 'GET',
            success: function (result) {
                if (result.success) {
                    $('#alertasDiv').load('@Url.Action("_Alertas","Base")');

                    if (result.recarga) {
                        RecargaListaTemporal();
                    }
                }
            }
        });
    }


    $("#MOLT").on("click", function (e) {
        $('#ULLT').toggle('slow');
        return false;
    });

    $("#recargaListaTemporal").on("click", function (e) {
        RecargaListaTemporal();
    });


    function RecargaListaTemporal() {
        var myUrl = '@Url.Action("RenderListaTemporal","Listado",null)';
        var contenedor = '#render_listaTemporal';
        //$(render_listaTemporal).html('Cargando Lista....');
        $(contenedor).load(myUrl);
    }
</script>



<script type="text/javascript">

    $('#FormFiltros').submit(function () {

        //alert(this.action);

        $('#render_resultadoPiezas').html('' +
            '<div class="text-center">' +
                '<p>' +
                    '<span class="text-muted">' +
                        'Por favor espere' +
                    '</span>' +
                '</p>' +
                '<i class="fa fa-spinner fa-pulse fa-12x text-muted"></i>' +
                '<p>' +
                    'Se estan procesando los resultados...' +
                '</p>' +
            '</div>');

        //alert(this.action);

        $('#pag').val(1);
        var myUrl = '@Url.Action("MostrarResultadosListado","Buscador",null)';
        $.ajax({
            url: myUrl,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                $('#render_resultadoPiezas').html(result); //  Campo que actualizara
            }
        });
        return false;
    });

</script>



@*<script type="text/javascript">

        $('#FormFiltros').submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    $('#renderResultadosBusqueda').html(result); //  Campo que actualizara
                }
            });
            return false;
        });

    </script>*@

RecordFCS/RecordFCS/Views/Listado/PDF_TextoPlano.cshtml
@model List<RecordFCS.Models.ViewsModel.itemListaBasicaDefault>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Html_PDF.cshtml";
    //    var imagePath = Server.MapPath("~/Content/Images");
}

<h1>Titulo h1</h1>
<span>Normal</span>
<small>small</small>



<table style="">
    <tr style="background-color: #000000; color:white;">
        <td><small>No. Inv</small></td>
        <td><small>Obra</small></td>
        <td><small>Titulo</small></td>
        <td><small>Autor</small></td>
        <td><small>Tecnica</small></td>
        <td><small>Medida</small></td>
        <td><small>Fecha</small></td>
        <td><small>Ubicacion</small></td>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td><small>@item.Pieza_clave</small></td>
            <td><small>@item.Obra_clave</small></td>
            <td><small>@item.Titulo</small></td>
            <td><small>@item.Autor</small></td>
            <td><small>@item.Tecnica</small></td>
            <td><small>@item.Medida</small></td>
            <td><small>@item.Fecha</small></td>
            <td><small>@item.Ubicacion</small></td>

        </tr>
    }
</table>

RecordFCS/RecordFCS/Views/Listado/_ListaEtiquetas.cshtml
@using RecordFCS.Helpers
@using RecordFCS.Models.ViewsModel
@model List<itemPiezaGenerica>

@Styles.Render("~/Content/css")
<link href="~/Content/list_Etiqueta.css" rel="stylesheet" />
<link href="~/Content/font-awesome.css" rel="stylesheet" />
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/jquery")


<div class="container">

    @foreach (var item in Model)
    {
        <div class="well well-sm contenedor-etiqueta">
            <div class="row">
                <div class="col-lg-2 col-md-3 col-sm-4 col-xs-4">

                    <img src="@item.RutaImagen" alt="@item.PiezaID" class="img-etiqueta" />
                </div>

                <div class="col-lg-10 col-md-9 col-sm-8 col-xs-8">
                    <table>
                        <tr>
                            <td>
                                <b>@item.ObraClave</b> - @item.PiezaClave
                            </td>
                        </tr>
                        @foreach (var campo in item.itemPiezaGenericaCampos)
                        {
                            <tr>
                                <td>
                                    @campo.ValorCampo
                                </td>
                            </tr>
                        }

                    </table>
                </div>

            </div>
        </div>
    }


</div>


@Scripts.Render("~/bundles/bootstrap")

RecordFCS/RecordFCS/Views/Listado/_ListaTemporal.cshtml
@using RecordFCS.Helpers
@model List<IGrouping<long, RecordFCS.Models.ViewsModel.PiezaEnCarrito>>

<span id="TotalLT" class="badge">@ViewBag.totalLT</span>

@*<ul class="media-list" id="ULLT">
        @foreach (var grupo in Model)
        {
            <li class="media" id="gLT_@grupo.Key">
                <div class="media-left">
                    dd
                </div>
                <div class="media-middle">
                    d
                </div>
                <div class="media-body">


                    No. de Inventario
                    <a href="@Url.Action("Detalles", "Obra", new { id = grupo.Key })" class="mediaGP-left">
                        <b>@grupo.Key</b>
                    </a>
                    <ul class="media-list">


                        @foreach (var item in grupo)
                        {
                            <li class="media" id="itemLt_@item.PiezaID">
                                <div class="media-left">
                                    <img src="@item.RutaImagen" alt="@item.ClaveObra" class="media-object img-mini">
                                </div>
                                <div class="media-body">
                                    <small class="media-heading"><b>@item.ClavePieza</b></small>
                                    <small class="center-block">@item.Titulo</small>
                                    <small class="center-block"><b>@item.Autor</b></small>
                                </div>
                                <div class="media-right">
                                    @Html.NoEncodeActionLink("<span class='fa fa-times'></span>", "Quitar Pieza", "PiezaDel", "Listado", new { PiezaID = item.PiezaID }, new { data_toggle = "tooltip", @Class = "link link-danger llamarRenderLTDEL" })
                                </div>
                            </li>
                        }
                    </ul>
                </div>

            </li>
        }
    </ul>*@


<ul class="media-list" id="ULLT">
    @foreach (var grupo in Model)
    {
        <li class="media LTPadre" id="gLT_@grupo.Key">
            <div class="media-left">
                <a href="@Url.Action("Detalles", "Obra", new { id = grupo.Key })" data-toggle="tooltip" title="Abrir Ficha" target="_blank"><b>@grupo.FirstOrDefault().ClaveObra</b></a>

            </div>

            <div class="media-body">

                <ul class="media-list">
                    @foreach (var item in grupo)
                    {
                        <li class="media LTHijo" id="itemLt_@item.PiezaID">
                            <div class="media-left"><img src="@item.RutaImagen" alt="@item.ClaveObra" class="media-object img-mini"></div>
                            <div class="media-body">
                                <small class="media-heading"><b>@item.ClavePieza</b></small>
                                <small class="center-block">@item.Titulo</small>
                                <small class="center-block"><b>@item.Autor</b></small>
                            </div>

                            <a href="@Url.Action("PiezaDel", "Listado", new { PiezaID = item.PiezaID })" class="media-right LTHijo llamarRenderLTDEL" data-toggle="tooltip" title="Quitar Pieza"><i class="fa fa-times" id="contVertical"></i></a>

                        </li>
                    }
                </ul>


            </div>
        </li>
    }
</ul>




<script type="text/javascript">
    $("a.llamarRenderLTDEL").one("click", function (e) {
        $.ajaxSetup({ cache: false });
        enviarInfoAjaxyRecargaLT($(this).attr('href'));
        return false;
    });
</script>

<script src="~/Scripts/holder.js"></script>

<script type="text/javascript">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>

RecordFCS/RecordFCS/Views/Listado/_MenuImprimir.cshtml
@model RecordFCS.Models.ViewsModel.OpcionesImprimir

@{
    ViewBag.PagName = "Menu de impresión en ";
    ViewBag.CtrlName = Model.Accion;
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">
        <b>@ViewBag.PagName </b>
        <i class="text-muted">@ViewBag.CtrlName</i>
        <span class="badge">@Model.NoElementos</span>
        <span> registros.</span>

    </h4>
</div>

@using (Html.BeginForm("GenerarFormato", "Listado", FormMethod.Post, new { id = "FormImprimir", name = "FormImprimir", target = "_blank" }))
{
    <div class="modal-body">

        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.Accion)
            @Html.HiddenFor(model => model.NombreLista)
            @Html.HiddenFor(model => model.NoElementos)

            <div class="form-group">
                @Html.LabelFor(model => model.NoColumnas, "No. de Columnas", new { @class = "control-label col-md-2" })
                <div class="col-lg-10">
                    @Html.DropDownListFor(model => model.NoColumnas, new SelectList(new List<Object> { new { value = 1, text = "Una Columna" }, new { value = 2, text = "Dos Columnas" } }, "value", "text", Model.NoColumnas), new { @class = "form-control" })
                </div>
            </div>


            <div class="form-group">
                <label class="col-lg-2 control-label">Datos</label>
                <div class="col-lg-10">
                    <div class="radio">
                        <label class="col-md-4 col-sm-4 col-xs-4" for="MostrarDatos_0">
                            @Html.RadioButtonFor(model => model.MostrarDatos, 0, new { id = "MostrarDatos_0", @class = "control-radio" })
                            Básicos
                        </label>

                        <label class="col-md-4 col-sm-4 col-xs-4" for="MostrarDatos_1">
                            @Html.RadioButtonFor(model => model.MostrarDatos, 1, new { id = "MostrarDatos_1", @class = "control-radio" })
                            Completos
                        </label>

                        <div class="col-md-4 col-sm-4 col-xs-4">
                        </div>

                    </div>
                </div>
            </div>


            <div class="form-group">
                <label class="col-lg-2 control-label">Obra</label>
                <div class="col-lg-10">
                    <div class="checkbox">
                        <label class="col-md-5 col-sm-5 col-xs-5">
                            @Html.CheckBoxFor(model => model.IncluirPiezas)
                            Incluir todas sus piezas
                        </label>

                        <label class="col-md-3 col-sm-3 col-xs-3" for="Unir_0">
                            @Html.RadioButtonFor(model => model.Unir, 0, new { id = "Unir_0", @class = "control-radio" })
                            Sin Unirlas
                        </label>

                        <label class="col-md-3 col-sm-3 col-xs-3" for="Unir_1">
                            @Html.RadioButtonFor(model => model.Unir, 1, new { id = "Unir_1", @class = "control-radio" })
                            Unirlas
                        </label>
                    </div>
                    <span class="help-block">[Sin Unirlas] Imprime las piezas por separado de su obra</span>
                </div>

            </div>


            <div class="form-group">
                <label class="col-lg-2 control-label">Adicional</label>
                <div class="col-lg-10">
                    <div class="checkbox">
                        <label class="col-md-4 col-sm-4 col-xs-4">
                            @Html.CheckBoxFor(model => model.Ubicacion)
                            Ubicación Actual
                        </label>


                        <label class="col-md-4 col-sm-4 col-xs-4">
                            @Html.CheckBoxFor(model => model.Fecha)
                            Fecha
                        </label>

                        <label class="col-md-4 col-sm-4 col-xs-4">
                        </label>
                    </div>
                </div>
            </div>




            <div class="form-group">
                <label class="col-lg-2 control-label">Líneas</label>
                <div class="col-lg-10">
                    <div class="radio">

                        <label class="col-md-4 col-sm-4 col-xs-4" for="Linea_0">
                            @Html.RadioButtonFor(model => model.Linea, 0, new { id = "Linea_0", @class = "control-radio" })
                            Ninguna
                        </label>

                        <label class="col-md-4 col-sm-4 col-xs-4" for="Linea_1">
                            @Html.RadioButtonFor(model => model.Linea, 1, new { id = "Linea_1", @class = "control-radio" })
                            Simple ______
                        </label>

                        <label class="col-md-4 col-sm-4 col-xs-4" for="Linea_2">
                            @Html.RadioButtonFor(model => model.Linea, 2, new { id = "Linea_2", @class = "control-radio" })
                            Recorte _ _ _ _
                        </label>

                    </div>
                    <span class="help-block">Lineas que separan las Obras</span>
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.NombreLogotipo, "Logotipo", new { @class = "control-label col-md-2" })
                <div class="col-lg-10">
                    @Html.DropDownListFor(model => model.NombreLogotipo, new SelectList(new List<Object> { new { value = 1, text = "Record Museo Soumaya" }, new { value = 2, text = "Record Fundación Carlos Slim" } }, "value", "text", Model.NombreLogotipo), new { @class = "form-control" })

                    <label>
                        @Html.CheckBoxFor(model => model.FondoAgua)
                        Incluirlo tambien como fondo de agua
                    </label>
                </div>
            </div>



            <div id="renderEspera"></div>

        </div>

    </div>

    <div class="modal-footer">
        <button class="btn" type="button" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-print"></i> Imprimir</button>

    </div>
}







<script type="text/javascript">

    $('#FormImprimir').submit(function () {

        //alert(this.action);
        var datos = "";

        $('#renderEspera').html('' +
            '<div class="text-center">' +
                '<p>' +
                    '<span class="text-muted">' +
                        'Por favor espere' +
                    '</span>' +
                '</p>' +
                '<i class="fa fa-spinner fa-pulse fa-2x text-muted"></i>' +
            '</div>');

        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {

                $('#FormImprimir').html('' +
            '<div class="text-center">' +
                '<p>' +
                    '<span class="text-success">' +
                        'Archivo Generado' +
                    '</span>' +
                '</p>' +
                '</div>');


                var win = window.open('about:blank');

                with (win.document) {
                    open();
                    write(result);
                    close();
                }
            }
        });

        return false;
    });

</script>